name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          cache-dependency-glob: "pyproject.toml"

      - name: Ruff Check
        run: uvx ruff check . --select ALL --line-length 150

      - name: Run Tests
        run: |
          uv venv --python python3.10 venv
          uv pip install --python venv pytest
          uv pip install --python venv pymodbus-waveshare-relay/.
          venv/bin/pytest pymodbus-waveshare-relay
          
          
          
          
