name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

#      - name: Cache uv environment
#        uses: actions/cache@v5
#        with:
#          path: |
#            ~/.cache/uv
#          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Ruff Check
        run: uvx ruff check . --select ALL --line-length 150